config/routes.rb
Rails.application.routes.draw do
  root 'feeds#index'

  resources :feeds, shallow: true do
    patch :fetch
    resources :items, only: %i(index show) do
      put :check
      put :uncheck
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :title, presence: true
  validates :url, presence: true

  def fetch_and_update
    feed = Feedjira::Feed.fetch_and_parse(self.url)
    feed.entries.reverse_each do |entry|
      item = self.items.find_or_initialize_by(url: entry.url)
      item.update(title: entry.title, published_at: entry.published)
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :feed

  validates :title, presence: true
  validates :url, presence: true, uniqueness: {scope: :feed_id}

  def check
    self.update(checked: true)
  end

  def uncheck
    self.update(checked: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: %i(show edit update destroy fetch)

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fetch
    @feed.fetch_and_update
    respond_to do |format|
      format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
      format.json { head :no_content }
    end
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end

    def feed_params
      params.require(:feed).permit(:title, :url)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :check, :uncheck]

  # GET /feeds/:feed_id/items
  # GET /feeds/:feed_id/items.json
  def index
    @feed = Feed.find(params[:feed_id])
    @items = @feed.items
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  def check
    @item.check
    respond_to do |format|
      format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
      format.json { head :no_content }
    end
  end

  def uncheck
    @item.uncheck
    respond_to do |format|
      format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
      format.json { head :no_content }
    end
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title, :url, :published_at, :feed_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.title %></td>
        <td><%= feed.url %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Checked</th>
      <th>Published at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td>
          <%= link_to item.title, item.url, target: :new %>
        </td>
        <td><%= item.checked %></td>
        <td><%= item.published_at %></td>
        <td><%= link_to 'Show', item %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @item.url %>
</p>

<p>
  <strong>Checked:</strong>
  <%= @item.checked %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @item.published_at %>
</p>

<p>
  <strong>Feed:</strong>
  <%= @item.feed %>
</p>

<%= link_to 'Back', feed_items_path(@item.feed) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rsss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>